### ISSUE TITLE
Delay to sigkill

### ISSUE THREAD

**Issue by AlmiS** [fhunleth/muontrap#22]
Hi,
We use Muontrap in our application to monitor some daemon processes, and everything works fine. 
However we are experiencing some issues in regards to the way shutdown of running processes is behaving.

According to: 
https://github.com/fhunleth/muontrap/blob/32edad41c9956e85d19db143942b06b57950147d/lib/muontrap.ex#L56
the `:delay_to_sigkill` option is documented as  `milliseconds before sending a SIGKILL to a child process if it doesn't exit with a SIGTERM`. 

This option is passed on unmodified as a `--delay-to-sigkill` argument here: 
https://github.com/fhunleth/muontrap/blob/32edad41c9956e85d19db143942b06b57950147d/lib/muontrap/port.ex#L56

However from the switch case here: 
https://github.com/fhunleth/muontrap/blob/38f5b417e365f80a38882cafb0692adaee199691/src/muontrap.c#L585-L590
it seems that `--delay-to-sigkill` is expected to be `Specified in microseconds for legacy reasons`. So in the end the option is interpreted as microseconds and not millisecond as stated in the documentation.

Apart from this, the switch case also for some unapparent reason forces the delay to be less than 1 second. This is really a big issue for us, as the processes we are running need more time for closing open files and shutting down gracefully.

Is there a reason why the delay before sending sigkill cannot be more than 1 second?

**Comment by fhunleth** [comment]
Thanks for digging into this and for posting a really detailed issue.

The "legacy" reason for microseconds and the one second timeout is too old and makes no sense. I had forgotten about that. 

I think deleting the lines checking that the `brutal_kill_wait_ms` is less than a second is an easy change and if you want to PR it, I'll merge it quickly. 

I'm also for getting rid of the legacy microseconds and bumping the version number to indicate a  breaking change. I want to check some code that uses muontrap first just in case there's something I'm missing. I'll try to do that some time this weekend.

**Comment by AlmiS** [comment]
Thank you for a quick response. I will open a PR to remove the check some time during this weekend.
